AllCops:
  NewCops: disable
  TargetRubyVersion: 3.2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/AccessModifierDeclarations:
  EnforcedStyle: group

Style/Documentation:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/LineLength:
  Exclude:
    - 'spec/**/*.rb'
